### ISSUE TITLE
Activate with key (triggerhappy) instead of play

### ISSUE THREAD

**Issue by krimikael** [SANGERA2/mpdcron-sleep-enabler#2]
Man this is great, just what i was looking for.
Would it be possible to run sleep after a triggerhappy command ?
Instead of activating the timer at play, activating after a simple pushbutton on the keyboard connected to the volumio player ?
Thanks !

**Comment by ScriptSorcererUK** [comment]
You can run the python command from the command line from anywhere. It looks like it's possible to run it when a specific key is pressed using the triggerhappy configs. https://community.volumio.com/t/guide-keyboard-shortcuts-with-triggerhappy/4826

**Comment by krimikael** [comment]
Which means i can/have to deactivate that it will run at boot ? 
sudo systemctl disable /lib/system.d/system/mpdcron.service 

And something like this in triggerhappy config ?
KEY_A 1 sudo systemctl start mpdcron.service

**Comment by ScriptSorcererUK** [comment]
You don't need to install or use mpdcron just make it run the python file /usr/local/bin/activate_sleep.py that's what mpdcron runs to enable sleep.

I don't know anything about triggerhappy though.
