### ISSUE TITLE
nano player doesnt contain any colums

### ISSUE THREAD

**Issue by krimikael** [SANGERA2/mpdcron-sleep-enabler#3]
![Screenshot from 2024-01-12 19-50-35](https://github.com/SANGERA2/mpdcron-sleep-enabler/assets/115104234/b46d7b56-a354-46f3-add2-323337fa92aa)

All the code is in one line, no idea if this is causing this error i have : 
Same with mpd_sleep_time.txt

```
volumio@rogue32:/usr/local/bin$ ./activate_sleep.py 
./activate_sleep.py: line 1: payload:allShortcutsEnabled:false: command not found
```

**Comment by ScriptSorcererUK** [comment]
It should definitely not all be on one line. Maybe download it using wget or copy and paste from the raw.

https://raw.githubusercontent.com/SANGERA2/mpdcron-sleep-enabler/main/mpdcron_in_home/hooks/player

**Comment by krimikael** [comment]
Thank you, works now
