### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by krimikael** [SANGERA2/mpdcron-sleep-enabler#5]
Just did this install again on an other pi.

`cd /lib/system.d/system`
should be 
`cd /lib/systemd/system`
as system.d is not a folder in Volumio ? 
After i changed this the code works.

`pip3 install -U socketIO-client `
-> needs sudo, not sure if needed for your code but i had to install it with sudo to use activate_sleep.py with triggerhappy.

**Comment by ScriptSorcererUK** [comment]
Thanks very much. That's really helpful. I was basically writing the guide from memory! I've updated the readme and the file paths in github.


Andy
