### ISSUE TITLE
Pause instead of sleep

### ISSUE THREAD

**Issue by krimikael** [SANGERA2/mpdcron-sleep-enabler#6]
Pause instead of sleep

I noticed that my rpi shutsdown after the sleep timer has been completed.
Can i change this to going to pause instead of sleep ?
Can you advise me where to look ?

Thanks in advance.

Changing the sleep settings in Volumio doesnt work (Default setting = Stop music)

**Comment by ScriptSorcererUK** [comment]
I'd advise checking the volumio forums and help or even posting on their github/forum. It may be a bug with the version of Volumio you're using.
